alertmanager:
  enabled: false

prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    nodeSelector:
      workload: flink
    podMonitorSelectorNilUseHelmValues: false
    retention: 6h
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi

grafana:
  service:
    type: ClusterIP
  nodeSelector:
    workload: flink
  sidecar:
    datasources:
      defaultDatasourceEnabled: false
  additionalDataSources:
  - name: Prometheus
    uid: PBFA97CFB590B2093
    type: prometheus
    access: proxy
    url: http://prom-kube-prometheus-stack-prometheus.manager:9090/
    isDefault: true
    jsonData:
      timeInterval: 30s

kube-state-metrics:
  nodeSelector:
    workload: flink
